version: "3.8"

x-volume-helper: &volume-helper
  driver: local
  driver_opts:
    type: none
    device: ${HOME}/.docker/archibald
    o: bind

services:
  app:
    build:
      context: .
      target: development
      dockerfile: Dockerfile
    platform: linux/amd64 # Change to linux/arm64 for ARM-based systems
    ports:
      - "5173:5173" # Vite dev server port
    volumes:
      - .:/app
      - app_node_modules:/app/node_modules # Named volume for node_modules
      - app_cache:/app/.cache # Named volume for build cache
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true # Enable hot reload on Docker
      - VITE_APP_VERSION=${npm_package_version:-0.0.0}
      - VITE_APP_NAME=Archibald
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:5173"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2G
        reservations:
          cpus: "0.5"
          memory: 512M
    restart: unless-stopped
    stdin_open: true # docker run -i
    tty: true # docker run -t
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  app_node_modules:
    <<: *volume-helper
    name: archibald_app_node_modules
    driver_opts:
      device: ${HOME}/.docker/archibald/app_node_modules
  app_cache:
    <<: *volume-helper
    name: archibald_app_cache
    driver_opts:
      device: ${HOME}/.docker/archibald/app_cache

# Add more services here as needed (e.g., mock API, database, etc.)

networks:
  default:
    name: archibald-network
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: archibald0
